package com.fatec.siga.constants.enumeration;

public enum SubjectEnumeration {
    // DSM-1
    MODELAGEM_BANCO_DE_DADOS,
    DESENVOLVIMENTO_WEB_I,
    ALGORTIMO_LOGICA_PROGRAMACAO,
    ENGENHARIA_SOFTWARE_I,
    DESIGN_DIGITAL,
    SISTEMAS_OPERACIONAIS_REDES_DE_COMPUTADORES,

    // DSM-2
    BANCO_DE_DADOS_RELACIONAL,
    DESENVOLVIMENTO_WEB_II,
    TECNICAS_PROGRAMACAO_I,
    ENGENHARIA_SOFTWARE_II,
    ESTRUTURA_DE_DADOS,
    MATEMATICA_COMPUTACAO,

    // DSM-3
    BANCO_DE_DADOS_NAO_RELACIONAL,
    DESENVOLVIMENTO_WEB_III,
    TECNICAS_PROGRAMACAO_II,
    GESTAO_AGIL_PROJETOS_SOFTWARE,
    INTERACAO_HUMANO_COMPUTADOR,
    ALGEBRA_LINEAR,
    INGLES_I,

    // DSM-4
    INTEGRACAO_ENTREGA_CONTINUA,
    LABORATORIO_DESENVOLVIMENTO_WEB,
    PROGRAMACAO_DISPOSITIVOS_MOVEIS_I,
    INTERNET_DAS_COISAS,
    EXPERIENCIA_USUARIO,
    ESTATISTICA_APLICADA,
    INGLES_II,

    // DSM-5
    SEGURANCA_DESENVOLVIMENTO_DE_APLICACOES,
    LABORATORIO_DESENVOLVIMENTO_MOVEIS,
    PROGRAMACAO_DISPOSITIVOS_MOVEIS_II,
    APRENDIZAGEM_MAQUINA,
    COMPUTACAO_NUVEM_I,
    FUNDAMENTOS_RREDACAO_TECNICA,
    INGLES_III,

    // DSM-6
    MINERACAO_DE_DADOS,
    LABORATORIO_DESENVOLVIMENTO_MULTIPLATAFORMA_REMOTO,
    LABORATORIO_DESENVOLVIMENTO_MULTIPLATAFORMA_PRESENCIAL,
    QUALIDADE_TESTE_SOFTWARE,
    PROCESSAMENTO_LINGUAGEM_NATURAL,
    COMPUTACAO_NUVEM_II,
    ETICA_PROFISSIONAL_PATENTE,
    INGLES_IV
}
